#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Kaede Ichikawa
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0

for line in sys.argv[1:]:
    try:
        ans += int(line)
    except: #Errormessage 
        print(f"error! 数値を入力して下さい:{line}")


# 3桁区切りで結果を出力
ans = '{:,}'.format(ans)
print(ans)
